"""Hypothesis module — generate novel scientific hypotheses from existing claims.

The HypothesisModule produces hypotheses that connect claims in novel
ways. Each hypothesis is structured as:

- A statement
- The claims on which it builds
- A testable prediction
- An experiment that would test the prediction
- A confidence value (typically low — hypotheses are speculative)

Hypotheses are *not* assertions of fact. They are registered in the
Claim Graph with low confidence and high epistemic uncertainty.
"""

from __future__ import annotations

from typing import Any

from nexus.core.types import Interpretation
from nexus.intelligence.base import IntelligenceModule


class HypothesisModule(IntelligenceModule):
    name = "hypothesis"

    SYSTEM_PROMPT = (
        "You are Nexus's HypothesisModule. Your job is to generate "
        "novel, testable scientific hypotheses that connect existing "
        "claims in non-obvious ways. You must:\n"
        "1. State the hypothesis in one sentence.\n"
        "2. List the claims on which it builds.\n"
        "3. State a testable prediction.\n"
        "4. Propose a concrete experiment that would test the prediction.\n"
        "5. Provide a confidence value (typically 0.2-0.4 - hypotheses "
        "are speculative by design).\n"
        "6. Never present a hypothesis as a fact."
    )

    async def run(
        self,
        question: str,
        context: dict[str, Any] | None = None,
    ) -> Interpretation:
        ctx = context or {}
        claim_ids = ctx.get("claim_ids", [])
        retrieved_knowledge = ctx.get("retrieved_knowledge", [])

        user_prompt = self._build_user_prompt(
            question=question,
            claim_ids=claim_ids,
            retrieved_knowledge=retrieved_knowledge,
        )
        messages = self._build_messages(self.SYSTEM_PROMPT, user_prompt, ctx)
        answer = await self._complete(messages, temperature=0.7, max_tokens=512)

        return self._make_interpretation(
            answer=answer,
            evidence_ids=claim_ids,
            retrieved_knowledge=retrieved_knowledge,
            inference="Hypothesis generated by connecting input claims in a novel way.",
            explanation="Hypotheses are speculative. Each hypothesis must be tested "
            "experimentally before being treated as a candidate claim.",
            alternatives=[
                "The null hypothesis (no relationship between the input claims).",
                "The inverse hypothesis (the opposite relationship).",
            ],
            contradictions=[
                "Hypotheses are by nature contradicted by the absence of supporting evidence.",
            ],
            recommended_next_step="Design and run the proposed experiment to test the hypothesis.",
            confidence_value=0.3,
        )

    @staticmethod
    def _build_user_prompt(
        question: str,
        claim_ids: list[str],
        retrieved_knowledge: list[str],
    ) -> str:
        claims_block = "\n".join(f"- {cid}" for cid in claim_ids) or "(no claims)"
        knowledge_block = "\n".join(f"- {k}" for k in retrieved_knowledge) or "(none)"
        return (
            f"Question: {question}\n\n"
            f"Available claims:\n{claims_block}\n\n"
            f"Retrieved knowledge:\n{knowledge_block}\n\n"
            f"Generate one novel, testable hypothesis."
        )


__all__ = ["HypothesisModule"]
